# Global 全局配置
site_analytics: ''
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: ''
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
check_update: true
# canonical: true

vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 2.14.1
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1

# 自定义样式
customStyles:
  images: # 图片相关设置
    # banner: /images/banner.webp # 站点横幅
    # background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
topMenu:
  - label: 首页
    icon: home
    url: /
  - label: 档案馆
    icon: file
    url: /archives/
  - label: 关于我
    icon: user
    url: /about/
  # - label: 好伙伴
  #   icon: paw
  #   url: /friends/
  # - label: 链接
  #   icon: link
  #   submenu:
  #     - label: 主页
  #       url: https://github.com/Ouroboros5664
  #     - label: 项目链接
  #       url: https://github.com/Candinya/Kratos-Rebirth

group_link: https://matrix.to/#/#CandyUnion:nya.one
footerLinks:
  - icon: github
    link: https://github.com/Candinya
  - html: <svg fill="currentColor" viewBox="0 0 1024 1024"><path d="M512,0C794.58,0 1024,229.42 1024,512C1024,794.58 794.58,1024 512,1024C229.42,1024 0,794.58 0,512C0,229.42 229.42,0 512,0ZM292.789,304.042L292.789,723.567C292.789,750.225 314.432,771.868 341.091,771.868C367.749,771.868 389.393,750.225 389.393,723.567L389.393,440.596L641.699,748.461C650.156,762.483 665.536,771.868 683.091,771.868C709.749,771.868 731.393,750.225 731.393,723.567L731.393,304.042C731.393,277.384 709.749,255.74 683.091,255.74C664.98,255.74 649.184,265.729 640.916,280.494L565.431,372.601L565.452,372.618C558.836,380.884 554.877,391.367 554.877,402.768C554.877,429.426 576.521,451.07 603.179,451.07C615.262,451.07 626.315,446.624 634.789,439.28L634.789,587.625L383.634,281.165C375.473,266.033 359.474,255.74 341.091,255.74C314.432,255.74 292.789,277.384 292.789,304.042Z" /></svg>
    link: https://nya.one/@Candinya
  - icon: rss
    link: /atom.xml
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: ''
    enableBGImage: false
  wordCount: 
    enable: true
    threshold: 1500

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: #后端服务器地址，必填
  comment: true
  pageview: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

#默认不计算hash 但是如果id过长(默认为url_for(page.path))会导致创建评论区失败 见[#139](https://github.com/Candinya/Kratos-Rebirth/issues/139)
gitalk_id_hasher: false
# gitalk_id_hasher: md5

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.webp
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      baseUrl: null # 使用默认值（不单独配置），将跟随 vendors 中的相关设定选择是否使用 cdn
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2018/05/06 17:03:12"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# Friends 友链相关内容
# friends:
#   href: "friends"
#   page:
#     title: "好伙伴们"
#     comments: false
#     description: "好伙伴们在哪里~"
#     updated: "2021-01-18"
#   list:
#   - name: "猫猫①号"
#     bio: "喵~"
#     avatar: "../images/avatar.webp"
#     link: "https://candinya.com"
#   - name: "猫猫②号"
#     bio: "喵喵~"
#     avatar: "../images/avatar.webp"
#     link: "https://candinya.com"
#   - name: "猫猫⑨号"
#     bio: "咪啪~"
#     avatar: "../images/avatar.webp"
#     link: "https://candinya.com"
#   verify: true # 验证每个友链的可访问性，炸了会有提示


# Misc 杂项
misc:
  showWordCountEstimateWavy: true # 在文章字数处显示表示大约字数的波浪号
